all: createTree_ConsensusTrees_simulations.cpp
	g++ createTree_ConsensusTrees_simulations.cpp -openmp -g -o consensusTrees
	@echo "Please execute next command line:"
	@echo './consensusTrees -tree nameFile_trees'

clean: 
	$(RM) consensusTrees